throwErrorOnExtraParameters: false

resourceBundle: Report
defaultToSvg: true

templates:
    A4 portrait: !template
        reportTemplate: pdfextract.jrxml
        outputFilename: ${yyyyMMddhhmmss}_extract
        pdfA: true
        attributes:
            CreationDate: !string {}
            Signature: !string &optStr
                default: ''
            ConcernedTheme: !datasource
                attributes:
                    Code: !string {}
                    Text: !string {} #/definitions/LocalisedText
            NotConcernedTheme: !datasource
                default:
                  - Code: 'Code not concerned'
                    Text: 'Theme theme not concerned'
                attributes:
                    Code: !string {}
                    Text: !string {} #/definitions/LocalisedText
            ThemeWithoutData: !datasource
                default:
                  - Code: 'Code without data'
                    Text: 'Theme without data'
                attributes:
                    Code: !string {}
                    Text: !string {} #/definitions/LocalisedText
            nbTocPages: !integer {}
            LogoPLRCadastre: *optStr
            LogoPLRCadastreRef: *optStr
            FederalLogo: *optStr
            FederalLogoRef: *optStr
            CantonalLogo: *optStr
            CantonalLogoRef: *optStr
            MunicipalityLogo: *optStr
            MunicipalityLogoRef: *optStr
            PrintCantonLogo: !boolean {}
            ExtractIdentifier: !string {}
            Certification: *optStr #/definitions/MultilingualMText
            CertificationAtWeb: *optStr #/definitions/MultilingualMText
            Footer: !string {}
            QRCode: *optStr
            QRCodeRef: *optStr
            GeneralInformation: !string #/definitions/MultilingualMText
                default: 'Disclaimer'
            UpdateDateOS: !string {}
            Glossary: !datasource
                default:
                  - Title: 'No term'
                    Content: 'No definition'
                attributes:
                    Title: !string {} #/definitions/MultilingualText
                    Content: !string {} #/definitions/MultilingualText
            RealEstate_Number: !string {}
            RealEstate_IdentDN: !string {}
            RealEstate_EGRID: !string {}
            RealEstate_Type_Text: !string {}
            RealEstate_Canton: !string {}
            RealEstate_Municipality: !string {}
            RealEstate_SubunitOfLandRegister: *optStr
            Display_RealEstate_SubunitOfLandRegister: !boolean
                default: true
            Display_Certification: !boolean
                default: true
            RealEstate_FosNr: !string {}
            RealEstate_MetadataOfGeographicalBaseData: *optStr
            RealEstate_LandRegistryArea: !string {}
            RealEstate_RestrictionOnLandownership: !datasource
                default: []
                attributes:
                    Legend: !datasource
                        attributes:
                            TypeCode: *optStr #/definitions/RestrictiontypeCode
                            TypeCodelist: *optStr
                            Geom_Type: !string {}
                            AreaShare: *optStr #/definitions/AreaShare
                            PartInPercent: *optStr
                            LengthShare: *optStr
                            NrOfPoints: *optStr
                            SymbolRef: *optStr
                            LegendText: *optStr #/definitions/MultilingualMText
                    OtherLegend: !datasource
                        default: []
                        attributes:
                            TypeCode: *optStr #/definitions/RestrictiontypeCode
                            SymbolRef: *optStr
                            LegendText: *optStr #/definitions/MultilingualMText
                    Geom_Type: *optStr
                    Theme_Code: *optStr
                    Theme_Text: *optStr #/definitions/LocalisedText
                    Lawstatus_Code: *optStr
                    Lawstatus_Text: *optStr #/definitions/LocalisedText
                    Symbol: *optStr
                    map: !map
                        maxDpi: 254
                        dpiSuggestions: [254]
                        width: 493
                        height: 280
                        default:
                            projection: "EPSG:2056"
                            dpi: 254
                            zoomToFeatures:
                                minScale: 0
                                minMargin: 10 # This value must be the same as the pyramid_oereb print buffer.
                    baseLayers: !staticLayers {}

                    ResponsibleOffice_Name: *optStr #/definitions/MultilingualText
                    ResponsibleOffice_OfficeAtWeb: *optStr #/definitions/WebReference
                    ResponsibleOffice_UID: *optStr #/definitions/UID
                    ResponsibleOffice_Line1: *optStr
                    ResponsibleOffice_Line2: *optStr
                    ResponsibleOffice_Street: *optStr
                    ResponsibleOffice_Number: *optStr
                    ResponsibleOffice_PostalCode: *optStr
                    ResponsibleOffice_City: *optStr
                    LegalProvisions: !datasource
                        default: []
                        attributes: &lpra
                            TextAtWeb: !datasource
                                default: []
                                attributes:
                                    URL: *optStr #/definitions/MultilingualUri
                            Lawstatus_Code: *optStr
                            Lawstatus_Text: *optStr #/definitions/LocalisedText
                            Number: *optStr #/definitions/ArticleNumber
                            Text: *optStr #/definitions/MultilingualMText
                            Title: *optStr #/definitions/MultilingualText
                            Abbreviation: *optStr #/definitions/MultilingualText
                            OfficialNumber: *optStr
                            Canton: *optStr #/definitions/CantonCode
                            Municipality: *optStr #/definitions/MunicipalityCode
                            ResponsibleOffice_Name: !string {} #/definitions/MultilingualText
                            ResponsibleOffice_OfficeAtWeb: *optStr #/definitions/WebReference
                            ResponsibleOffice_UID: *optStr #/definitions/UID
                            ResponsibleOffice_Line1: *optStr
                            ResponsibleOffice_Line2: *optStr
                            ResponsibleOffice_Street: *optStr
                            ResponsibleOffice_Number: *optStr
                            ResponsibleOffice_PostalCode: *optStr
                            ResponsibleOffice_City: *optStr
                            OfficialNumber: *optStr #/definitions/CantonCode
                            ArticleNumber: *optStr #array of /definitions/ArticleNumber
                    Hints: !datasource
                        default: []
                        attributes: *lpra
                    Laws: !datasource
                        default: []
                        attributes: *lpra
                    ResponsibleOffice: !datasource
                        default: []
                        attributes:
                            Name: !string {}
                            OfficeAtWeb: *optStr
            DisclaimerLandRegister_Title: !string {}
            DisclaimerLandRegister_Content: !string {}
            DisclaimerPollutedSites_Title: !string {}
            DisclaimerPollutedSites_Content: !string {}
            PLRCadastreAuthority_Name: !string {} #/definitions/MultilingualText
            PLRCadastreAuthority_OfficeAtWeb: *optStr #/definitions/WebReference
            PLRCadastreAuthority_UID: *optStr #/definitions/UID
            PLRCadastreAuthority_Line1: *optStr
            PLRCadastreAuthority_Line2: *optStr
            PLRCadastreAuthority_Street: !string {}
            PLRCadastreAuthority_Number: !string {}
            PLRCadastreAuthority_PostalCode: !string {}
            PLRCadastreAuthority_City: !string {}
            MultiPageTOC: !boolean
                default: false

            northArrow: !northArrow
                size: 17
                default:
                    graphic: "file:///north.svg"
            scalebar: !scalebar
                width: 100
                height: 15
                default:
                  fontSize: 6
                  align: "center"
                  padding: 2
                  lineWidth: 1
                  backgroundColor: "rgb(255, 255, 255)"
            features: !features {}
            map: !map
                maxDpi: 254
                dpiSuggestions: [254]
                width: 493
                height: 280
                default:
                    projection: "EPSG:2056"
                    dpi: 254
                    zoomToFeatures:
                        minScale: 0
                        minMargin: 10 # This value must be the same as the pyramid_oereb print buffer.
            baseLayers: !staticLayers {}
            overlayLayers: !staticLayers
                default:
                    layers:
                    -   type: geoJson
            style: !style
                default:
                    style:
                        version: 2
                        '*':
                            symbolizers:
                            -   type: polygon
                                fillColor: "#ff0000"
                                fillOpacity: 0.0
                                strokeColor: "#e60000"
                                strokeOpacity: 0.60
                                strokeWidth: 5

        processors:
        - !reportBuilder # compile all reports in current directory
            directory: '.'
        - !configureHttpRequests
            httpProcessors:
            - !mapUri # NEEDED FOR DOCKER ENVIRONMENT
                mapping:
                  (https?)://localhost:6543/(.*): "http://oereb-server:6543/$2"
            - !mapUri # NEEDED FOR DOCKER ENVIRONMENT (Oereblex port)
                mapping:
                  (https?)://localhost:6544/(.*): "http://oereb-server:6543/$2"
            - !forwardHeaders
                headers:
                - Referer
        - !addOverlayLayers
            inputMapper:
                overlayLayers: staticLayers
        - !addBackgroundLayers
            inputMapper:
                baseLayers: staticLayers
        - !setStyle {}
        - !setFeatures {}
        - !createMap {}
        - !createNorthArrow {}
        - !createScalebar {}
        - !createDataSource
            processors: []
            inputMapper:
                ConcernedTheme: datasource
            outputMapper:
                jrDataSource: ConcernedThemeDataSource
        - !createDataSource
            processors: []
            inputMapper:
                NotConcernedTheme: datasource
            outputMapper:
                jrDataSource: NotConcernedThemeDataSource
        - !createDataSource
            processors: []
            inputMapper:
                ThemeWithoutData: datasource
            outputMapper:
                jrDataSource: ThemeWithoutDataDataSource
        - !createDataSource
            processors: []
            inputMapper:
                Glossary: datasource
            outputMapper:
                jrDataSource: GlossaryDataSource
        - !createDataSource
            copyAttributes: [overlayLayers, style, features]
            processors:
            - !createDataSource
                processors: []
                inputMapper:
                    Legend: datasource
                outputMapper:
                    jrDataSource: LegendDataSource
            - !createDataSource
                processors: []
                inputMapper:
                    OtherLegend: datasource
                outputMapper:
                    jrDataSource: OtherLegendDataSource
            - !createDataSource
                processors: &dsrc
                - !createDataSource
                    processors: []
                    inputMapper:
                        TextAtWeb: datasource
                    outputMapper:
                        jrDataSource: TextAtWebDataSource
                inputMapper:
                    LegalProvisions: datasource
                outputMapper:
                    jrDataSource: LegalProvisionsDataSource
            - !createDataSource
                processors: *dsrc
                inputMapper:
                    Hints: datasource
                outputMapper:
                    jrDataSource: HintsDataSource
            - !createDataSource
                processors: *dsrc
                inputMapper:
                    Laws: datasource
                outputMapper:
                    jrDataSource: LawsDataSource
            - !createDataSource
                processors: []
                inputMapper:
                    ResponsibleOffice: datasource
                outputMapper:
                    jrDataSource: ResponsibleOfficeDataSource
            - !addOverlayLayers
                inputMapper:
                    overlayLayers: staticLayers
            - !addBackgroundLayers
                inputMapper:
                    baseLayers: staticLayers
            - !setStyle {}
            - !setFeatures {}
            - !createMap {}
            inputMapper:
                RealEstate_RestrictionOnLandownership: datasource
            outputMapper:
                jrDataSource: RealEstate_RestrictionOnLandownershipDataSource
